### ISSUE TITLE
Keyboard input stops responding

### ISSUE THREAD

**Issue by ant-druha** [JetBrains/ideolog#19]
Reported to IntelliJ support:

Hitting Shift-Z locks keyboard from any input log attached below:

```
2017-11-05 03:30:59,117 [239640621] ERROR - llij.ide.plugins.PluginManager - -1 
java.lang.ArrayIndexOutOfBoundsException: -1 
at java.text.DigitList.fitsIntoLong(DigitList.java:230) 
at java.text.DecimalFormat.parse(DecimalFormat.java:2049) 
at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2162) 
at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514) 
at java.text.DateFormat.parse(DateFormat.java:364) 
at com.intellij.ideolog.lex.LogFileFormat.parseLogEventTimeSeconds(LogFileFormats.kt:66) 
at com.intellij.ideolog.highlighting.LogHighlightingIterator.reparsePieces(LogFileHighlighterFactory.kt:169) 
at com.intellij.ideolog.highlighting.LogHighlightingIterator.<init>(LogFileHighlighterFactory.kt:110) 
at com.intellij.ideolog.highlighting.LogEditorHighlighter.createIterator(LogFileHighlighterFactory.kt:60) 
at com.intellij.openapi.editor.impl.view.IterationState.<init>(IterationState.java:144) 
at com.intellij.openapi.editor.impl.view.EditorPainter.a(EditorPainter.java:949) 
at com.intellij.openapi.editor.impl.view.EditorPainter.b(EditorPainter.java:374) 
at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:106) 
at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:266) 
at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1683) 
at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:241) 
at javax.swing.JComponent.paint(JComponent.java:1056) 
at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:127) 
at javax.swing.JComponent.paintChildren(JComponent.java:889) 
at javax.swing.JComponent.paint(JComponent.java:1065) 
at javax.swing.JViewport.paint(JViewport.java:728) 
at com.intellij.ui.components.JBViewport.paint(JBViewport.java:230) 
at javax.swing.JComponent.paintChildren(JComponent.java:889) 
at javax.swing.JComponent.paint(JComponent.java:1065) 
at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) 
at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) 
at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) 
at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306) 
at javax.swing.RepaintManager.paint(RepaintManager.java:1272) 
at javax.swing.JComponent._paintImmediately(JComponent.java:5158) 
at javax.swing.JComponent.paintImmediately(JComponent.java:4969) 
at javax.swing.RepaintManager$4.run(RepaintManager.java:831) 
at javax.swing.RepaintManager$4.run(RepaintManager.java:814) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 
at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) 
at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) 
at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) 
at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) 
at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) 
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) 
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762) 
at java.awt.EventQueue.access$500(EventQueue.java:98) 
at java.awt.EventQueue$3.run(EventQueue.java:715) 
at java.awt.EventQueue$3.run(EventQueue.java:709) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 
at java.awt.EventQueue.dispatchEvent(EventQueue.java:732) 
at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821) 
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649) 
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365) 
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
2017-11-05 03:30:59,118 [239640622] ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2017.2.5 Build #IU-172.4343.14 
2017-11-05 03:30:59,118 [239640622] ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2017-11-05 03:30:59,118 [239640622] ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2017-11-05 03:30:59,118 [239640622] ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2017-11-05 03:30:59,118 [239640622] ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2017-11-05 03:30:59,118 [239640622] ERROR - llij.ide.plugins.PluginManager - Last Action: ShowLog 
2017-11-05 03:30:59,174 [239640678] ERROR - llij.ide.plugins.PluginManager - -1 
java.lang.ArrayIndexOutOfBoundsException: -1 
at java.text.DigitList.fitsIntoLong(DigitList.java:230) 
at java.text.DecimalFormat.parse(DecimalFormat.java:2049) 
at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1869) 
at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514) 
at java.text.DateFormat.parse(DateFormat.java:364) 
at com.intellij.ideolog.lex.LogFileFormat.parseLogEventTimeSeconds(LogFileFormats.kt:66) 
at com.intellij.ideolog.highlighting.LogHighlightingIterator.reparsePieces(LogFileHighlighterFactory.kt:169) 
at com.intellij.ideolog.highlighting.LogHighlightingIterator.<init>(LogFileHighlighterFactory.kt:110) 
at com.intellij.ideolog.highlighting.LogEditorHighlighter.createIterator(LogFileHighlighterFactory.kt:60) 
at com.intellij.openapi.editor.impl.view.IterationState.<init>(IterationState.java:144) 
at com.intellij.openapi.editor.impl.view.EditorPainter.a(EditorPainter.java:949) 
at com.intellij.openapi.editor.impl.view.EditorPainter.a(EditorPainter.java:186) 
at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:100) 
at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:266) 
at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1683) 
at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:241) 
at javax.swing.JComponent.paint(JComponent.java:1056) 
at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:127) 
at javax.swing.JComponent.paintChildren(JComponent.java:889) 
at javax.swing.JComponent.paint(JComponent.java:1065) 
at javax.swing.JViewport.paint(JViewport.java:728) 
at com.intellij.ui.components.JBViewport.paint(JBViewport.java:230) 
at javax.swing.JComponent.paintChildren(JComponent.java:889) 
at javax.swing.JComponent.paint(JComponent.java:1065) 
at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) 
at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) 
at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) 
at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306) 
at javax.swing.RepaintManager.paint(RepaintManager.java:1272) 
at javax.swing.JComponent._paintImmediately(JComponent.java:5158) 
at javax.swing.JComponent.paintImmediately(JComponent.java:4969) 
at javax.swing.RepaintManager$4.run(RepaintManager.java:831) 
at javax.swing.RepaintManager$4.run(RepaintManager.java:814) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 
at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) 
at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) 
at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) 
at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) 
at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) 
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) 
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762) 
at java.awt.EventQueue.access$500(EventQueue.java:98) 
at java.awt.EventQueue$3.run(EventQueue.java:715) 
at java.awt.EventQueue$3.run(EventQueue.java:709) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) 
at java.awt.EventQueue.dispatchEvent(EventQueue.java:732) 
at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821) 
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649) 
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365) 
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
2017-11-05 03:30:59,174 [239640678] ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2017.2.5 Build #IU-172.4343.14 
2017-11-05 03:30:59,174 [239640678] ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2017-11-05 03:30:59,174 [239640678] ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2017-11-05 03:30:59,174 [239640678] ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2017-11-05 03:30:59,175 [239640679] ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2017-11-05 03:30:59,175 [239640679] ERROR - llij.ide.plugins.PluginManager - Last Action: ShowLog
```

**Comment by knah** [comment]
Fixed in 7a882d82fa839bd9f4ddb0daa19bdbcefe840d11
