### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Wrong offset: 48. Should be in range: [0, 47]

### ISSUE THREAD

**Issue by ignatov** [JetBrains/ideolog#7]
Wrong offset: 48. Should be in range: [0, 47]
java.lang.IndexOutOfBoundsException: Wrong offset: 48. Should be in range: [0, 47]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:174)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:887)
	at com.intellij.ideolog.highlighting.LogParsingUtils.findEventStartOffset(LogParsingUtils.kt:126)
	at com.intellij.ideolog.highlighting.LogParsingUtils.getEvent(LogParsingUtils.kt:114)
	at com.intellij.ideolog.highlighting.LogParsingUtils.getEvent$default(LogParsingUtils.kt:113)
	at com.intellij.ideolog.highlighting.LogHighlightingIterator.parseNextEvent(LogFileHighlighterFactory.kt:134)
	at com.intellij.ideolog.highlighting.LogHighlightingIterator.advance(LogFileHighlighterFactory.kt:353)
	at com.intellij.openapi.editor.impl.view.IterationState.getHighlighterEnd(IterationState.java:324)
	at com.intellij.openapi.editor.impl.view.IterationState.advance(IterationState.java:289)
	at com.intellij.openapi.editor.impl.view.LineLayout$Chunk.ensureLayout(LineLayout.java:642)
	at com.intellij.openapi.editor.impl.view.LineLayout$Chunk.access$2800(LineLayout.java:599)
	at com.intellij.openapi.editor.impl.view.LineLayout$VisualOrderIterator.hasNext(LineLayout.java:737)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.hasNext(VisualLineFragmentsIterator.java:214)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.logicalToVisualPosition(EditorCoordinateMapper.java:81)
	at com.intellij.openapi.editor.impl.view.EditorView.logicalToVisualPosition(EditorView.java:171)
	at com.intellij.openapi.editor.impl.EditorImpl.logicalToVisualPosition(EditorImpl.java:1987)
	at com.intellij.openapi.editor.impl.CaretImpl.updateCachedStateIfNeeded(CaretImpl.java:1510)
	at com.intellij.openapi.editor.impl.CaretImpl.getVisualPosition(CaretImpl.java:691)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.lambda$getPreferredSize$0(EditorSizeManager.java:181)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:461)
	at java.util.stream.IntPipeline.max(IntPipeline.java:424)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.getPreferredSize(EditorSizeManager.java:182)
	at com.intellij.openapi.editor.impl.view.EditorView.getPreferredSize(EditorView.java:278)
	at com.intellij.openapi.editor.impl.EditorImpl.getPreferredSize(EditorImpl.java:1890)
	at com.intellij.openapi.editor.impl.EditorImpl.validateSize(EditorImpl.java:1554)
	at com.intellij.openapi.editor.impl.EditorImpl.changedUpdate(EditorImpl.java:1466)
	at com.intellij.openapi.editor.impl.EditorImpl.access$11700(EditorImpl.java:137)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter.documentChanged(EditorImpl.java:4401)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:779)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:712)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:580)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:527)
	at com.intellij.codeInsight.intention.impl.config.ActionUsagePanel.configureByText(ActionUsagePanel.java:91)
	at com.intellij.codeInsight.intention.impl.config.ActionUsagePanel.lambda$null$0(ActionUsagePanel.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.util.DocumentUtil.lambda$writeInRunUndoTransparentAction$0(DocumentUtil.java:62)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:323)
	at com.intellij.util.DocumentUtil.writeInRunUndoTransparentAction(DocumentUtil.java:62)
	at com.intellij.codeInsight.intention.impl.config.ActionUsagePanel.lambda$reset$1(ActionUsagePanel.java:84)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$null$1(MacOSApplicationProvider.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$submit$6(MacOSApplicationProvider.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.IndexOutOfBoundsException: Wrong offset: 48. Should be in range: [0, 47]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:174)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:887)
	at com.intellij.ideolog.highlighting.LogParsingUtils.findEventStartOffset(LogParsingUtils.kt:126)
	at com.intellij.ideolog.highlighting.LogParsingUtils.getEvent(LogParsingUtils.kt:114)
	at com.intellij.ideolog.highlighting.LogParsingUtils.getEvent$default(LogParsingUtils.kt:113)
	at com.intellij.ideolog.highlighting.LogHighlightingIterator.parseNextEvent(LogFileHighlighterFactory.kt:134)
	at com.intellij.ideolog.highlighting.LogHighlightingIterator.advance(LogFileHighlighterFactory.kt:353)
	at com.intellij.openapi.editor.impl.view.IterationState.getHighlighterEnd(IterationState.java:324)
	at com.intellij.openapi.editor.impl.view.IterationState.advance(IterationState.java:289)
	at com.intellij.openapi.editor.impl.view.LineLayout$Chunk.ensureLayout(LineLayout.java:642)
	at com.intellij.openapi.editor.impl.view.LineLayout$Chunk.access$2800(LineLayout.java:599)
	at com.intellij.openapi.editor.impl.view.LineLayout$VisualOrderIterator.hasNext(LineLayout.java:737)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.hasNext(VisualLineFragmentsIterator.java:214)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.logicalToVisualPosition(EditorCoordinateMapper.java:81)
	at com.intellij.openapi.editor.impl.view.EditorView.logicalToVisualPosition(EditorView.java:171)
	at com.intellij.openapi.editor.impl.EditorImpl.logicalToVisualPosition(EditorImpl.java:1987)
	at com.intellij.openapi.editor.impl.CaretImpl.updateCachedStateIfNeeded(CaretImpl.java:1510)
	at com.intellij.openapi.editor.impl.CaretImpl.getVisualPosition(CaretImpl.java:691)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.lambda$getPreferredSize$0(EditorSizeManager.java:181)
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:461)
	at java.util.stream.IntPipeline.max(IntPipeline.java:424)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.getPreferredSize(EditorSizeManager.java:182)
	at com.intellij.openapi.editor.impl.view.EditorView.getPreferredSize(EditorView.java:278)
	at com.intellij.openapi.editor.impl.EditorImpl.getPreferredSize(EditorImpl.java:1890)
	at com.intellij.openapi.editor.impl.EditorImpl.validateSize(EditorImpl.java:1554)
	at com.intellij.openapi.editor.impl.EditorImpl.changedUpdate(EditorImpl.java:1466)
	at com.intellij.openapi.editor.impl.EditorImpl.access$11700(EditorImpl.java:137)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter.documentChanged(EditorImpl.java:4401)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:779)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:712)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:580)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:527)
	at com.intellij.codeInsight.intention.impl.config.ActionUsagePanel.configureByText(ActionUsagePanel.java:91)
	at com.intellij.codeInsight.intention.impl.config.ActionUsagePanel.lambda$null$0(ActionUsagePanel.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.util.DocumentUtil.lambda$writeInRunUndoTransparentAction$0(DocumentUtil.java:62)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:323)
	at com.intellij.util.DocumentUtil.writeInRunUndoTransparentAction(DocumentUtil.java:62)
	at com.intellij.codeInsight.intention.impl.config.ActionUsagePanel.lambda$reset$1(ActionUsagePanel.java:84)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$null$1(MacOSApplicationProvider.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$submit$6(MacOSApplicationProvider.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mfilippov** [comment]
Looks fixed.
