### ISSUE TITLE
Intention Description Dir URL is null: HideLinesNotContainingSubstringIntention

### ISSUE THREAD

**Issue by MaXal** [JetBrains/ideolog#90]
Plugin version: Ideolog (201.0.21.0)
IDE version:  PhpStorm (build #PS-202.1586, 27 Mar 2020 22:04) 

The following exception is thrown:
```
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Logs; HideLinesNotContainingSubstringIntention; while looking for description.html [Plugin: com.intellij.ideolog]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:63)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:126)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.lambda$processMetaData$0(IntentionManagerSettings.java:203)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834
```

**Comment by mfilippov** [comment]
Fixed in 201.0.22.0
